{{- if .Values.reviews.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bookinfo.reviews.serviceAccountName" . }}-reviews
  labels:
    {{- include "bookinfo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.reviews.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
